/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geracpf;

/**
 *
 * @author 311100469
 */
public class TelaTeste extends javax.swing.JFrame {

    public TelaTeste() {
        initComponents();        
    }
    
    public String calcula(String n){        
        String verificadores;
        int soma=0;
        int y=9;
        n=n.replace(".","");
 //fazendo digito 1-------------------------------------------------------------       
        for(int i=0; i<n.length();i++){
            int digito = Character.getNumericValue(n.charAt(i));            
            soma += digito * (i+1);
            System.out.println(digito+"x"+(i+1)+"="+(digito*(i+1)));
        }
        int digito1=soma%11;
        
        if(digito1==10){
            digito1=digito1%10;
        }
        soma=0;
        System.out.println("Soma = "+soma);
        System.out.println("--------");
  //fazendo digito 2-------------------------------------------------------------       
        for(int i=0; i<n.length();i++){
            int digito = Character.getNumericValue(n.charAt(i));
            soma+=digito *(y);
            System.out.println(digito+"x"+y+"="+(digito*y));
            y--;
        }
        System.out.println("Soma = "+soma);
        
        int digito2=soma%11;
        
        if(digito2==10){
            digito2=digito2%10;
        }
//----------------------------------------        
        
        
        System.out.println("digito 1 é '"+digito1+"' Digito 2 é '"+digito2+"'");
        verificadores = Integer.toString(digito1)+Integer.toString(digito2);
        System.out.println(verificadores);        
        
        return verificadores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numerosTextField = new javax.swing.JTextField();
        digitosFinaisLabel = new javax.swing.JLabel();
        calculaBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        numerosTextField.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        numerosTextField.setText("123.456.789");
        numerosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosTextFieldActionPerformed(evt);
            }
        });

        digitosFinaisLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        digitosFinaisLabel.setText("XX");

        calculaBut.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        calculaBut.setText("CALCULA");
        calculaBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numerosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(calculaBut)
                        .addGap(10, 10, 10)))
                .addGap(18, 18, 18)
                .addComponent(digitosFinaisLabel)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numerosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digitosFinaisLabel))
                .addGap(18, 18, 18)
                .addComponent(calculaBut)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numerosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosTextFieldActionPerformed

    private void calculaButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculaButActionPerformed
       String numeroCaixaTexto;
       
       numeroCaixaTexto=numerosTextField.getText();
       
        numeroCaixaTexto=calcula(numeroCaixaTexto);
        
        digitosFinaisLabel.setText(numeroCaixaTexto);
        
        
    }//GEN-LAST:event_calculaButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculaBut;
    private javax.swing.JLabel digitosFinaisLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numerosTextField;
    // End of variables declaration//GEN-END:variables
}
